config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # get  '/login', to: 'sessions#new'
  # post  '/login', to: 'sessions#create'
  # delete '/logout', to: 'sessions#destroy'

  resources :users, only: %i[create new show]
  resources :events, only: %i[create new show index]
  get 'sessions/new'
  get 'login', to: 'sessions#new'
  delete 'logout', to: 'sessions#destroy'
  post 'login', to: 'sessions#create'
  root to: 'sessions#new'
  post 'attendance', to: 'events#create_attendance'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :attendee, class_name: 'User'
  belongs_to :attended_events, class_name: 'Event'
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User'
  has_many :attendances, foreign_key: 'attended_events_id', class_name: 'Attendance'
  has_many :attendees, through: :attendances, source: :attendee

  scope :upcoming_events, -> { where('date >= ?', Date.today) }
  scope :past_events, -> { where('date < ?', Date.today) }

  validates :date, presence: true
  validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :created_events, class_name: 'Event', dependent: :destroy, foreign_key: 'creator_id'
  has_many :attendances, foreign_key: 'attendee_id'
  has_many :attended_events, through: :attendances

  validates :username, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    current_user
  end

  def require_login
    return if logged_in?

    flash[:danger] = 'Please login!'
    redirect_to login_path
  end

  def user_params
    params.require(:user).permit(:username)
  end

  def event_params
    params.require(:event).permit(:date, :description)
  end

  def attendance_params
    params.require(:attendance).permit(:attended_events_id)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :require_login, only: %i[create show]

  def index
    @event = Event.all
    @attendance = Attendance.new
    @past_events = Event.past_events
    @upcoming_events = Event.upcoming_events
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.created_events.build(event_params)

    if @event.save
      redirect_to event_path(@event)

    else
      render :new
    end
  end

  def show
    @event = Event.find(params[:id])
    @created_events = current_user.created_events
  end

  def create_attendance
    # raise params[:event_id]
    @attendance = current_user.attendances.find_or_initialize_by(attendance_params)

    if @attendance.save
      redirect_to root_path

    else
      render :new
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    # user=User.find_by(username: user_params[:username])
    @user = User.find_by(username: params[:session][:username])
    if @user
      session[:user_id] = @user.id
      flash[:notice] = "#{@user.username} succesfully logged in"
      redirect_to events_path
    else
      flash.now.alert = 'Login failed'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = 'You have successfully logged out.'
    redirect_to new_user_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: [:show]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to new_user_path

    else
      render :new
    end
  end

  def show
    @user = User.find_by(params[:username])
  end

  def destroy
    session.delete(:current_user)
    flash[:notice] = 'You have successfully logged out.'
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def attends?(event_id)
    current_user.attended_events.map(&:id).include? event_id
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<h3>Upcoming events </h3>
 <% @upcoming_events.each do |t| %>
  <%= t.description %>
  <br/>
  <% unless attends? t.id %>
   <%= form_with model: @attendance, url: attendance_path  do |f| %>
   <%= f.hidden_field :attended_events_id, value: t.id %> 
  
    <%= f.submit "Attend" %>
 
  
      <% end %>
<% end %>
<% end %>


<h3>Past events </h3>


 <%  @past_events.each do |event| %>
  
   <%= event.description %>
  <br>
 <% end %>

app/views/events/new.html.erb
 <%= form_for @event do |f| %>
    Date:      <%= f.date_field(:date) %>
    <br>
   Description: <%= f.text_field(:description) %>
  <br>
    <%= f.submit "Submit" %>
<% end %>

app/views/events/show.html.erb
<h4> Created Events </h4>
<% @created_events.each do |t| %>

  <%= t.description %>
  <br/>
<% end %>

<h4> Attendees </h4>
<% @event.attendees.each do |t| %>
  <%= t.username %>
<% end %>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
      <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

 
  </head>
 <body>
    <%= render 'users/navbar' %>
    <div class="container">
    <br>
    <%= yield %>
  </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/users/_navbar.html.erb
  <% flash.each do |type, message| %>
			<div><%= message %></div>
	<% end %>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
       
     
      </li>
      	<% if !logged_in? %>
           
						<%= link_to 'Log in', login_path, class: "nav-link" %>
                <li>
					<%= link_to "Sign up", new_user_path, class: "nav-link" %>
          </li>
					<% else %>
              <li><%= link_to 'Private events', events_path, class: "nav-link" %></li>
              <li>
              <%= link_to "Create event", new_event_path, class: "nav-link" %>
              </li>
              <li >
                <%= link_to 'Log out', logout_path, method: :delete, class: "nav-link" %>
                </li>
                <li >
                <%= link_to 'future or past events', events_path, class: "nav-link" %>
                </li>
					<% end %>
     
    </ul>
  </div>
</nav>

app/views/users/new.html.erb
 <%= form_for @user do |f| %>
    Username: <%= f.text_field :username %> 
  
    <%= f.submit "Submit" %>
  
<% end %>

app/views/users/show.html.erb
<h3>
<% @user.username%>
</h3>